fos_rest:
    serializer:
        serialize_null:  true
    param_fetcher_listener: true
    body_listener: true
    body_converter:
        enabled: true
    format_listener:
        enabled: true
        rules:
          - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
          - { path: '^/auth/register', priorities: ['json'], fallback_format: 'json' }
          - { path: '^/auth/authentication', priorities: ['json'], fallback_format: 'json' }
          - { path: '^/auth/login', priorities: ['html'], fallback_format: 'html' }
          - { path: '^/auth/logout', priorities: ['html'], fallback_format: 'html' }
          - { path: '^/', priorities: ['html'], fallback_format: 'html' }
    versioning: true
    view:
        view_response_listener: 'force'