fos_rest:
    serializer:
        serialize_null:  true
    param_fetcher_listener: true
    body_listener: true
    body_converter:
        enabled: true
    format_listener:
        enabled: true
        rules:
          - { path: '^/api', priorities: ['json'], fallback_format: 'html' }
          - { path: '^/auth', priorities: ['json'], fallback_format: 'html' }
          - { path: '^/', priorities: ['html', 'json'], fallback_format: 'html' }
    versioning: true
    view:
        view_response_listener: 'force'